name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.4.0
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
          ./gradlew assemble --no-daemon
